### ISSUE TITLE
gRPCでラズパイを動かしたい

### ISSUE THREAD

**Issue by Atori-Ikeyama** [p2hacks2023/post-06#3]
# ラズパイをgRPCで動かす方法を調査

**Comment by kokist** [comment]
- [x] Windowsでのサンプルプログラムの動作確認
- [x] ラズパイでの動作確認
- [x] Windowsとラズパイでやり取りできるか動作確認

[参考サイト](https://techblog.hys-neko-lab.com/entry/2022/06/25/105159)
